
### get all persons
GET http://localhost:8080/api/persons

### get specific persons
GET http://localhost:8080/api/persons/1

### create a new person
POST http://localhost:8080/api/persons
content-type: application/json

{
    "name": "John",
    "number": "123-232-43"
}

### delete specific persons
DELETE http://localhost:8080/api/persons/1

### get info
GET http://localhost:8080/info
